### ISSUE TITLE
Dedupe affliation script doesn't work for me

### ISSUE THREAD

**Issue by titipata** [titipata/grant_database#11]
@daniel-acuna, can you check [dedupe_affiliation.py](https://github.com/titipata/grant_database/blob/master/dedupe/dedupe_affiliation.py) in deduplication part. I got error when running the script as follows:

``` python
Traceback (most recent call last):
  File "dedupe_affiliation.py", line 94, in <module>
    deduper.train(ppc=None, recall=0.95)
  File "/Users/titipat/anaconda3/lib/python3.5/site-packages/dedupe/api.py", line 659, in train
    index_predicates)
  File "/Users/titipat/anaconda3/lib/python3.5/site-packages/dedupe/api.py", line 679, in _trainBlocker
    recall)
  File "/Users/titipat/anaconda3/lib/python3.5/site-packages/dedupe/training.py", line 102, in learn
    raise ValueError(NO_PREDICATES_ERROR)
ValueError: No predicate found! We could not learn a single good predicate. Maybe give Dedupe more training data or increasing the `max_comparisons` argument to the train method
```

**Comment by titipata** [comment]
fixed by 2662e967f145fa, I returned wrong dataframe in `merge_nsf_nih_df` function. It's now fixed
